test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID']%>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY']%>
  session_token: <%= ENV['AWS_SESSION_TOKEN']%>
  region: us-east-1
  bucket: francescperezvenegas

